---
- name: ubuntu
  hosts: all
  become: true
  become_method: sudo
  remote_user: ubuntu
  vars_files:
    - vars/default.yml

  tasks:
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/hw3.yml
